import io
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

def generate_compliance_pdf(case_data):
    """
    Generates a PDF Compliance Audit Report using ReportLab.
    Returns bytes buffer of the PDF file.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0f172a'),
        fontName='Helvetica-Bold'
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#475569'),
        fontName='Helvetica'
    )

    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#1e293b'),
        fontName='Helvetica-Bold',
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#334155'),
        fontName='Helvetica'
    )

    badge_style = ParagraphStyle(
        'BadgeText',
        parent=styles['Normal'],
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#065f46'),
        fontName='Helvetica-Bold'
    )

    # 1. Header Section
    story.append(Paragraph("BIS COMPLIANCE AUDIT REPORT", title_style))
    story.append(Paragraph("Official Compliance Intelligence & Citation Summary | Generated by BIS Compliance Copilot", subtitle_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563eb'), spaceAfter=15))

    # 2. Executive Summary Table
    product_name = case_data.get('product_name', 'Electric Kettle')
    is_number = case_data.get('is_number', 'IS 302-2-25')
    scheme = case_data.get('scheme', 'Scheme I (ISI Mark)')
    qco_status = case_data.get('qco_status', 'Compulsory Order Enforced')

    summary_table_data = [
        [Paragraph("<b>Parameter</b>", body_style), Paragraph("<b>Verified BIS Value</b>", body_style), Paragraph("<b>Verification Status</b>", body_style)],
        [Paragraph("Product Name", body_style), Paragraph(product_name, body_style), Paragraph("User Identified", body_style)],
        [Paragraph("Indian Standard", body_style), Paragraph(f"<b>{is_number}</b>", body_style), Paragraph("DETERMINISTIC GROUND TRUTH", badge_style)],
        [Paragraph("QCO Order Status", body_style), Paragraph(qco_status, body_style), Paragraph("COMPULSORY NOTICE", badge_style)],
        [Paragraph("Certification Scheme", body_style), Paragraph(scheme, body_style), Paragraph("MANDATORY SCHEME", badge_style)]
    ]

    t = Table(summary_table_data, colWidths=[130, 260, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#0f172a')),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 15))

    # 3. Mandatory Testing Roadmap
    story.append(Paragraph("Mandatory Testing & Quality Control Requirements", heading_style))
    checklist_items = case_data.get('checklist', [
        "Routine High Voltage Breakdown Test (Clause 13)",
        "Leakage Current Measurement under Operating Temp (Clause 16)",
        "Endurance & Thermal Cut-Off Verification (Clause 18)",
        "In-House Calibrated Testing Facilities Verification",
        "Scheme-I Factory Inspection & Sample Drawing Procedure"
    ])

    check_table_data = [[Paragraph("<b>#</b>", body_style), Paragraph("<b>Mandatory Quality & Testing Requirement</b>", body_style), Paragraph("<b>Status</b>", body_style)]]
    for idx, item in enumerate(checklist_items, 1):
        check_table_data.append([
            Paragraph(str(idx), body_style),
            Paragraph(item, body_style),
            Paragraph("Pending Lab Test", body_style)
        ])

    t2 = Table(check_table_data, colWidths=[30, 380, 130])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f8fafc')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t2)
    story.append(Spacer(1, 15))

    # 4. Citation Grounding Disclaimer
    story.append(Paragraph("Verifiable Evidence & Audit Disclaimer", heading_style))
    disclaimer_text = (
        "<b>Notice:</b> This compliance report was generated using the BIS Compliance Copilot hybrid engine. "
        "Deterministic outputs (Indian Standards, QCO applicability, Scheme requirements) are strictly mapped "
        "against verified public BIS notifications. Always verify current notifications on www.bis.gov.in before commercial production."
    )
    story.append(Paragraph(disclaimer_text, body_style))
    story.append(Spacer(1, 25))

    # 5. Signature Footer
    sig_data = [
        [Paragraph("<b>Prepared By:</b> BIS Compliance Copilot AI", body_style), Paragraph("<b>Approved By:</b> Manufacturer Compliance Officer", body_style)],
        [Paragraph("Date: 2026-09-01", body_style), Paragraph("Signature: ______________________", body_style)]
    ]
    t3 = Table(sig_data, colWidths=[270, 270])
    t3.setStyle(TableStyle([
        ('TOPPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t3)

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
